### ISSUE TITLE
Avoid needless copies?

### ISSUE THREAD

**Issue by vinniefalco** [danielaparker/jsoncons#156]
In the following `jsonpointer` example:

```
json result2 = jsonpointer::get(example, "/foo");
```

Is **result2** a copy? Or is it a non-owning reference to data owned by the `example` container?

**Comment by danielaparker** [comment]
On master, `jsonpointer::get` now returns references if applied to `basic_json`, and values if applied to `cbor_view` (`cbor_view` is a non-owning view into an array of bytes.)

Examples:

(1) On success, returns the selected item by reference, otherwise throws

    json j = json::array{"baz","foo"};
    json& item = jsonpointer::get(j,"/0"); // "baz"

(2) On success, returns the selected item by const reference, otherwise throws

    const json j = json::array{"baz","foo"};
    const json& item = jsonpointer::get(j,"/1"); // "foo"

(3) On success, returns the selected item by value, otherwise throws
  
    std::vector<uint8_t> b = {0x82,0x63,0x62,0x61,0x7a,0x63,0x66,0x6f,0x6f}; // in CBOR
    cbor::cbor_view bv = b;
    cbor::cbor_view item = jsonpointer::get(bv,"/0"); // "baz"

(4) On success, returns the selected item by reference, otherwise an undefined item by reference.  Error code is set on failure.

    json j = json::array{"baz","foo"};
    std::error_code ec;
    json& item = jsonpointer::get(j,"/1",ec); // "foo"

(5) On success, returns the selected item by const reference, otherwise an undefined item by const reference.  Error code is set on failure. 

    const json j = json::array{"baz","foo"};
    std::error_code ec;
    const json& item = jsonpointer::get(j,"/0",ec); // "baz"

(6) On success, returns the selected item by value, otherwise an undefined item by value. Error code is set on failure. 

    std::vector<uint8_t> b = {0x82,0x63,0x62,0x61,0x7a,0x63,0x66,0x6f,0x6f}; // in CBOR
    cbor::cbor_view bv = b;
    std::error_code ec; 
    cbor::cbor_view item = jsonpointer::get(bv,"/1",ec); // "foo"

**Comment by vinniefalco** [comment]
That is impressive work, and a very well written response! This should go into the documentation, if it hasn't already !
