### ISSUE TITLE
Playing around with CBOR, JSON, and CSV - VS 2017 and Master code 8/30/18

### ISSUE THREAD

**Issue by MavKillian** [danielaparker/jsoncons#162]
Is this an issue with the example "Playing around with CBOR, JSON, and CSV" or Visual Studio 2017?
I downloaded the latest master source code on 8/30/18 and receive the following error when I try to run/debug:

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2664	'std::string jsoncons::cbor::detail::get_text_string(const uint8_t *,const uint8_t *,const uint8_t **)': cannot convert argument 3 from 'unsigned char **' to 'const uint8_t **'	ConsoleApplication5	c:\users\killimm1\desktop\c code\jsoncons-master - final\jsoncons-master\include\jsoncons_ext\cbor\cbor_parser.hpp	1693

**Comment by danielaparker** [comment]
The "Playing around" example is in one of the example files,` readme_examples.cpp`, and I can build and run all of the example files in vs2017 without any warnings or errors at warning level 4.

The error that you're showing is caused by some code passing  'unsigned char **' where 'const uint8_t **' is expected, which vs2017 doesn't allow, which was one of the items in your earlier issue, and which I'm fairly certain has been fixed everywhere. Is it possible that the jsoncons header files you're compiling with are not actually the latest from master? Perhaps your build is picking up some older files? Please verify. 

Otherwise, I'd need you to post your ConsoleApplication5 code in full, since I can't replicate the error with the example file.

Thanks,
Daniel

**Comment by MavKillian** [comment]
Yes I removed the previous master version and replaced with the latest I called final. I can start a new application from scratch and use the example from readme instead of the copy paste I did to rule out anything from prior builds and hopefully that will work without errors. Will let you know, thanks again


-------- Original message --------
