### ISSUE TITLE
is_xxx family of member functions declared as noexcept, but throw

### ISSUE THREAD

**Issue by scobei** [danielaparker/jsoncons#184]
Firstly, I'm a big fan of the library and would love to see it included in vcpkg. Now, the is_xxx family of functions do not adhere to their contract. They are marked as **noexcept**, but do throw:

```		
jsoncons::json root = jsoncons::json::parse(R"({"key":"value"})");

// Thought this would be safe, but no.
auto j = root["key1"];
if (j.is_object()) // declared as noexcept, but throws 'key_not_found'
	{
	}

// I know one can do this safely, but it's kinda verbose
if (root.has_member("key1"))
	{
	auto j = root["key1"];
	if (j.is_object())
		{
		// do stuff
		}
	}

```

**Comment by danielaparker** [comment]
Thanks for the feedback.

`root["key1"]` returns a proxy to a `json`, which is evaluated lazily. If `root["key1"]` is undefined (there is no such member), and an accessor is called on the proxy, the proxy generally throws. But I agree with you that it should not throw for the accessors declared `noexcept`. I've changed those accessors so that the `is_xxx` functions will return `false` rather than throw on an undefined json proxy. This code is now on master.

However, when you write
```
auto j = root["key1"];
```
j is exactly what is returned, the proxy, and that is a problem. The proxy holds a pointer to the (possibly temporary) key data passed to `operator[]`, and the lifetime of that data is not guaranteed after the end of the full-expression `root["key1"]`.  That's unsafe. So, on master, I've made the copy and move constructors of the json proxy private, so that attempting to assign to an `auto` will now fail to compile. You should assign either to a `json` (for  a copy), or a `const json&` (for a const reference to the value) or a `json&` for a non-const reference. 

Perhaps you could write (with the code on master)
```c++
jsoncons::json root = jsoncons::json::parse(R"({"key":"value"})");

if (root["key1"].is_object())
{
    jsoncons::json& j = root["key1"];
}
```
By the way, use `contains("key1")` rather than `has_member("key1")`, `has_member` was deprecated some time ago.

Best regards,
Daniel

**Comment by scobei** [comment]
Thank you for your attention to this and for the tips! Don't see any recent commits to master that would affect this issue, though.

**Comment by danielaparker** [comment]
Ah, forgot to push it. It should be there now.

**Comment by scobei** [comment]
Perfect! Thanks again.
