### ISSUE TITLE
Polymorphic traits

### ISSUE THREAD

**Issue by patternoia** [danielaparker/jsoncons#192]
Dear Daniel,

thanks a lot for your recent changes for polymorphic classes.
However, I can not create traits for two classes deriving from same base in two separate calls.

E.g. this will not compile
```
JSONCONS_POLYMORPHIC_TRAITS_DECL(ns::BaseClass, ns::Derived) // header 1
JSONCONS_POLYMORPHIC_TRAITS_DECL(ns::BaseClass, ns::Derived2) // header 2
```

Is there any solution to this?

**Comment by danielaparker** [comment]
I thought about this, and compared with some other serialization frameworks, but there are technical difficulties with supporting separate declarations. The current approach is very easy to implement, as the generation of the traits specialization for smart pointers has all of the derived types. A decentralized approach requires a separate derived type registry, but difficulties arise because the registry doesn't know about the `json_type_traits` template parameter `Json`, which could be a custom user instantiation of `basic_json`.
