### ISSUE TITLE
Add support for constructing a byte_string_arg with a std::string

### ISSUE THREAD

**Issue by lrosenthol** [danielaparker/jsoncons#239]
In trying to place some binary data into a structure (for output to CBOR) I had to copy the data to a std::vector<uint8_t> to be able to make the byte_string.

I would be great if I could just pass in an `std::string`.

Even better would be a way to pass any form of `std::istream` that you could then read/iterate over byte by byte...

Also, if you are willing to take PRs, I am willing to start looking into doing some of this myself...

**Comment by danielaparker** [comment]
I've generalized the `basic_json(byte_string_arg_t, ...` constructor to allow any byte sequence argument, which is a container that has member functions `data()` and `size()`, and member type `value_type` with width of exactly 8 bits. Any of the values types `uint8_t`, `char`, `std::byte` (since C++17), and `char8_t` (since C++20) are now allowed. In particular, `std::string` is allowed,

```c++
std::string bytes = {'f','o','o','b','a','r'};
json j(byte_string_arg, bytes, semantic_tag::base64url);
```

Enhancement is on master.

**Comment by lrosenthol** [comment]
The byte_string_arg works perfectly, thanks.

I like the idea of supporting `decode_xxx` to accept any byte container, but why not the `encode` versions as well??

**Comment by danielaparker** [comment]
Since you asked :-)

I've generalized the functions `encode_bson`, `encode_cbor`, `encode_msgpack` and `encode_ubjson` to write to any back insertable byte container, which is a container that has member function `push_back()`, and member type `value_type` with width of exactly 8 bits. Any of the values types `int8_t`, `uint8_t`, `char`, `unsigned char` and `std::byte` (since C++17) are allowed.

**Comment by lrosenthol** [comment]
Amazing service - thank you!

Verified that, for my needs in JSON and CBOR, it is working perfectly.

Feel free to close.

**Comment by danielaparker** [comment]
Enhancement is in v0.152.0
