### ISSUE TITLE
amalgamated source

### ISSUE THREAD

**Issue by xelatihy** [danielaparker/jsoncons#278]
**Describe the proposed feature**

It would be nice to be able to deploy the library as single-header for simple projects.
Or maybe it would be more appropriate to have a file for JSON support and one for the extensions.

**What other libraries (C++ or other) have this feature?**

Json for Modern C++

**Include a code fragment with sample data that illustrates the use of this feature**

N/A

**Comment by danielaparker** [comment]
I'm uncertain about this. I'd like to hear from others if possible.

On the one hand, I'd agree that being able to download a single header file contributes to the popularity of [JSON for Modern C++](https://github.com/nlohmann/json), and is regarded as a welcome convenience for a subset of, perhaps a majority of, their users.

But I'm a little uneasy about that, because these libraries, which started out small, are getting huge. The JSON for Modern C++ amalgamated header file is now about 26,000 lines. jsoncons has more features than JSON for Modern C++, so I'd expect a single amalgamated header file to be significantly larger. Also, JSON for Modern C++ in its current form is more or less monolithic, I don't think you could include much without including everything, its various binary format readers, for example, are all in one (unamalgamated) `.hpp` file.  The jsoncons extensions, in contrast, are largely independent of each other, except for jsonpatch, which depends on jsonpointer. 

I suppose it would be feasible to have a post build process that would generate an amalgamated header for the include files under `jsoncons`. But many of our users use one or two of the extensions under `jsoncons_ext`, while hardly any use all of them. I would be reluctant to have an amalgamated header for all of the extensions. Particularly as the number of extensions will continue to grow, next on the list is yaml.

Any comments appreciated.

**Comment by xelatihy** [comment]
You make some very good point, most of which I am agreeing with. In the end, it is just a question of simplicity of installation right now. Let me comment quickly on some issues you pointed out.

The main issue of header-only libraries is that compilation times grow significantly as more code is added. For template-heavy code there is no fix. For functions with significant code that should be in cpp files, well header-only is a workaround to simplify builds.

As far as using amalgamated source versus not, many libraries that go that way provide both amalgamated sources and original source files. The former makes code easier to use. The latter makes it compile faster. The choice is left to the library users.

Some single-file libraries use include guards to disable features in the amalgamated source. The solution is practical and use extensively. I dislike for personal taste. But even this is just a way to reduce compilation time since all code is in the header, so  a tradeoff.

I went through many of these issues with my own library and, as it grew, I split into more files and move to cpp file as much code as possible. The latter was the bigger compilation speed up (compile times profiled with clang). I am not suggesting this change, but just that I understand all points made in the previous comment well.

As for package managers, at least in our work, we do not see that we are there yet.

In the end, it is just a convenience to have both file layouts (single-file and many-files) that are tradeoff between installation/build simplicity and compilation times. I am not sure one is better than the other. They offer different benefits and drawbacks.

In case you may want to proceed, I'd be happy to take a crack at it if you'd like.

**Comment by xelatihy** [comment]
I should add that I would also be happy to maintain a forked version of the repo with the amalgamated source. I tend to dislike this since it may fractures the users, although in this case we may be the only users of this feature.

**Comment by brlcad** [comment]
Just to chime in with some feedback... If the preprocessor needs to traverse all files, then single header vs multi is moot from a performance perspective.  If there's going to be a single header entry point, then it's moot from a calling code perspective.  There is an integration benefit for codes that want to just drop in a header file vs a directory of headers into a subdir, but I'd argue that's rather minor save for the smallest projects.

In my perspective, header-only matters but single header is not a consideration that will result in my using or not using jsoncons.  Things that matter much more: performance, input robustness, memory footprint, limitations.

**Comment by danielaparker** [comment]
I'm closing this one as I've no plans to work on it.
