### ISSUE TITLE
Assert triggers on key_value when using polymorphic allocator

### ISSUE THREAD

**Issue by royjacobson** [danielaparker/jsoncons#424]
Hi!

the following code - 

```c++
#include "jsoncons/json.hpp"
#include <memory>
#include <memory_resource>

struct pmr_sorted_policy : public jsoncons::sorted_policy {
  template <class T, class Allocator> using vector = std::pmr::vector<T>;

  template <class KeyT, class Json>
  using sorted_json_object = jsoncons::sorted_json_object<KeyT, Json, vector>;

  template <class Json> using array = jsoncons::json_array<Json, vector>;

  template <class CharT, class CharTraits, class Allocator>
  using string = std::pmr::basic_string<CharT>;
};

using custom_json = jsoncons::basic_json<char, pmr_sorted_policy,
                                         std::pmr::polymorphic_allocator<char>>;

static custom_json j;
```

triggers the following assert in libstdc++:

```c++
      static_assert(__or_<
	  is_constructible<_Tp, allocator_arg_t, const _Alloc&, _Args...>,
	  is_constructible<_Tp, _Args..., const _Alloc&>>::value,
	  "construction with an allocator must be possible"
	  " if uses_allocator is true");
``` 

It seems to complain about `jsoncons::key_value` that has a member `allocator_type` but has no related allocator constructors. Should the relevant constructors be added to `jsoncons::key_value`?

**Comment by danielaparker** [comment]
Thanks for reporting this. The issues it raises are related to #419.

The first issue is that `key_value` shouldn't have an `allocator_type` member. I've removed it on master.

I need to think about the next issue.

**Comment by danielaparker** [comment]
After studying the issue, it seems to me that it's difficult for jsoncons to support both "bare" stateful allocators on the one hand, and polymorphic and scoped allocators on the other. Basically, it's because of the different behavior of `emplace_back` (and the other emplace functions) in the standard library container classes, especially `std::vector`, which we use as a backing store. With a bare stateful allocator, it's required that the caller provide the allocator; with polymorphic and scoped allocators, it's required that the caller _not_ provide the allocator.  

When working directly with standard library classes, it's up to the user to supply or omit the allocator argument, e.g., to supply it in this case
```
    std::vector<string_with_stateful_allocator_type, stateful_allocator_type> v(stateful_allocator);
    v.emplace_back("Hello World", stateful_allocator);
```
and to omit it in these ones,
```
    std::vector<string_with_polymorphic_allocator_type, polymorphic_allocator_type> v(polymorphic_allocator);
    v.emplace_back("Hello World");

    std::vector<string_with_scoped_allocator_type, scoped_allocator_type> v(scoped_allocator);
    v.emplace_back("Hello World");
```
In the jsoncons library, it's more complicated than that, because calls to `emplace_back` are also happening within internal code, where we wouldn't know whether we need to pass the allocator or not. In internal code, we don't know what kind of an allocator that we have (other than whether it's stateless or not, we detect that.)

I'm considering whether it would be better to change the library to support

- stateless allocators (as presently)

- polymorphic allocators

and drop support for bare stateful allocators, unless wrapped in a scoped allocator adaptor. In some respects this would simplify the internal code. 

This is the main consideration. The observed static asserts are simply the result of the standard library
not finding the required constructors with an allocator argument in the right place, and these are
easily addressed, providing we don't try to support both the bare stateful allocators and the others.

**Comment by danielaparker** [comment]
We've added support for [std::pmr::polymorphic_allocator](https://en.cppreference.com/w/cpp/memory/polymorphic_allocator) and [std::scoped_allocator_adaptor](https://en.cppreference.com/w/cpp/memory/scoped_allocator_adaptor) in branch [PolymorphicAllocator](https://github.com/danielaparker/jsoncons/tree/PolymorhicAllocator).

We've defined aliases and alias templates for `basic_json` using polymorphic allocators in the `jsoncons::pmr` namespace, see [basic_json](https://github.com/danielaparker/jsoncons/blob/PolymorhicAllocator/doc/ref/basic_json.md).

For examples of `polymorphic_allocator`, see [polymorphic_allocator_tests.cpp](https://github.com/danielaparker/jsoncons/blob/PolymorhicAllocator/test/corelib/src/polymorphic_allocator_tests.cpp).

For examples of `scoped_allocator_adaptor`, see [scoped_allocator_adaptor_tests.cpp](https://github.com/danielaparker/jsoncons/blob/PolymorhicAllocator/test/corelib/src/scoped_allocator_adaptor_tests.cpp).

Support for regular (non-propagating) stateful allocators has been dropped, non-propagating stateful allocators must now be wrapped with a `std::scoped_allocator_adaptor`. We've done that for our example with the boost interprocess allocator, see [the example](https://github.com/danielaparker/jsoncons/blob/PolymorhicAllocator/examples_boost/interprocess_allocator2/shared_memory.cpp). 

Non-stateful allocators are supported as before.

**Comment by danielaparker** [comment]
This is currently on master.
