### ISSUE TITLE
How to solve the problem of Chinese garbled characters

### ISSUE THREAD

**Issue by zhjr2019** [danielaparker/jsoncons#464]
**Describe the proposed feature**
Chinese garbled code

**What other libraries (C++ or other) have this feature?**

**Include a code fragment with sample data that illustrates the use of this feature**
```C++
#include <iostream>
#include <jsoncons/json.hpp>
#include <jsoncons_ext/bson/bson.hpp>
int main(int argc, char* argv[])
{
    jsoncons::json j;
    j.try_emplace("hello", "你好");
    std::cout << "(1)\n" << jsoncons::pretty_print(j) << "\n\n";
    
    std::vector<char> buffer;
    jsoncons::bson::encode_bson(j, buffer);
    std::cout << jsoncons::byte_string_view(buffer) << "\n\n";
    
    jsoncons::ojson oj = jsoncons::bson::decode_bson<jsoncons::ojson>(buffer);
    std::cout << "(2)\n" << jsoncons::pretty_print(oj) << "\n\n";
    
    system("pause");
    return EXIT_SUCCESS;
}
```
visual studio 2022;
windows 11;
![Snipaste_2023-10-07_13-57-24](https://github.com/danielaparker/jsoncons/assets/44044519/3f1a4bed-662f-453e-a771-00a34a22a2b3)

**Comment by danielaparker** [comment]
The string literal `"你好"` assumes ASCII characters, and the Chinese characters can't be represented in ASCII. To represent them as UTF-8, use `u8"你好"`.

Until C++ 20, UTF-8 string literals were of type `const char[N]`, and jsoncons allowed

```
j.try_emplace("hello", u8"你好");
``` 

However, since C++ 20, string literals are of type const `char8_t[N]`, and jsoncons doesn't currently support `char8_t`. But you can cast to `const char*`,

 ```
j.try_emplace("hello", (const char *)"你好");
```

**Comment by danielaparker** [comment]
With jsoncons 0.171.0 (preview on master) and C++ 20, we'll have support for `char8_t` and `std::u8string`, and you'll be able to write

```
jsoncons::json j;

std::u8string s = u8"你好";
 j.try_emplace("hello", s);
assert(j["hello"].as<std::u8string>() == s);
```
