### ISSUE TITLE
segfault when inserting a field into pmr::json

### ISSUE THREAD

**Issue by romange** [danielaparker/jsoncons#482]
**Describe the bug**

the code below crashes
```cpp
  pmr::json dest;
  dest["bar"] = "foo";
```

should not crash

**Enumerate the steps to reproduce the bug**

**Include a small, self-contained example if possible**

**What compiler, architecture, and operating system?**

- Compiler: ________
- Architecture (e.g. x86, x64) ____
- Operating system: linux

**What jsoncons library version?**

 - [ ] Latest release 0.173.2
 - [x] Other release v0.171.1
 - [ ] master

**Comment by romange** [comment]
The workaround it declare `json` object like this: `pmr::json dest{json_object_arg};`

**Comment by danielaparker** [comment]
`pmr::json dest` uses the default constructor, which creates an empty object, with no space allocated for members.

The statement

```
dest["bar"] = "foo";
```

attempts to add a member to the empty object. jsoncons attempts to allocate space for the member, but it will only do so if it detects that the allocator type is stateless, e.g. `std::allocator` or another allocator type that doesn't hold state. `std::pmr::polymorphic_allocator` is a stateful allocator, jsoncons detects that, and fails. I had intended that to be a compile time error, and so used a `static_assert`, but in fact the fault isn't detected until runtime, which is why you got no diagnostics. I've replaced the `static_assert` with a runtime exception in the main branch.

Normally you would create a `pmr::json` something like

```
std::pmr::polymorphic_allocator<char> alloc(&pool);

pmr::json dest(json_object_arg, alloc);
```

Then
```
dest["bar"] = "foo";
```

would use the memory resource `pool` that you provided.
