### ISSUE TITLE
.get("key",stringval).as<std::string>(); fails

### ISSUE THREAD

**Issue by Bigpet** [danielaparker/jsoncons#49]
on master this crashes for me on VS2013

    #include "jsoncons/json.hpp"
    #include <string>
    #include <iostream>
    
    using namespace jsoncons;
    using std::string;
    
    int main(int argc, char **argv)
    {
      json example;
      string result = example.get("test", string("too long string for short string")).as<string>();
      std::cout << "result:" << result << std::endl;
      return 0;
    }

Throws a `bad_alloc` on both master and the last tag during retrieving in `as<string>()`

**Comment by Bigpet** [comment]
well `json::const_val_proxy` is move and copy constructible 

    std::cout << "copy_constructible " << std::is_copy_constructible<json::const_val_proxy>::value << std::endl;
    std::cout << "move_constructible " << std::is_move_constructible<json::const_val_proxy>::value << std::endl;

The issue is its reference `other.val_` could or could not point to `other.val2_`, so the only safe thing to do would be to copy `other.val_` to `this->val2_` like so:

     const_val_proxy(const const_val_proxy&rhs) : val2_(rhs.val_), val_(val2_){}; 

same for a move-constructor. Alternatively `const_val_proxy` could carry a flag whether or not it owns whatever val1_ points to.

I guess this is one of those cases where a non-owning reference is just as suble as a non-owning pointer

**Comment by danielaparker** [comment]
Thanks for reporting this.

After revisiting get(name,default_val), I have to confess that I share your sentiment "the semantics of const_val_proxy are pretty confusing." I guess its original purpose was to delay the construction of the default json object, until it was determined that it was needed, but it was no longer doing that, if it ever did. So instead of taking your fix, I removed const_val_proxy altogether.

I had some difficulty getting a failing test case to test against, as VS 2015 was happy with your example. However, reverting to VS2013, the original code fails with your example, and the new code on master passes.

Thanks again,
Daniel

**Comment by sjiekak** [comment]
I have a similar issue (vs2015) in the `jsoncons::create_impl` function during

`std::allocator_traits<Alloc>:: template rebind_traits<T>::construct(alloc, storage, std::forward<Args>(args)...);`

**Comment by danielaparker** [comment]
Which version of jsoncons? Can you send me an example that shows the issue?

Daniel

**Comment by sjiekak** [comment]
Version 0.99.1. 
I'll try to create a minimal example.

**Comment by sjiekak** [comment]
After investigation it seems my bug wasn't caused by jsoncons.  My apologies.
