### ISSUE TITLE
Conformance report for reference

### ISSUE THREAD

**Issue by miloyip** [danielaparker/jsoncons#88]
https://github.com/miloyip/nativejson-benchmark/blob/master/sample/conformance_jsoncons%20(C%2B%2B).md

**Comment by danielaparker** [comment]
I appreciate the feedback, thanks.

Your report suggests five instances where jsoncons is non conformant in round-trip. 

Issues 1, 2, and 5 appear to be differences with input and output formatting, the presence or absence of a space between the colon and the value, and the presence or absence of a + sign in the exponential notation.  The input and output content, however, is the same, so I don't think these indicate non-conformance with [RFC7159](https://www.ietf.org/rfc/rfc7159.txt).

Issues 3 and 4 appear to be due to input numeric values lying outside the precision of int64_t and double respectively. 9223372036854775808 is one greater than `std::numeric_limits<int64_t>::max` in my environment, in which case jsoncons falls back on reading it as a double.  Similarly, 5e-324 is less than std::numeric_limits<double>::min.

Regarding matters of precision, [RFC7159](https://www.ietf.org/rfc/rfc7159.txt) states that "this specification allows implementations to set limits on the range and precision of numbers accepted.  Since software that implements IEEE 754-2008 binary64 (double precision) numbers [IEEE754] is generally available and widely used, good interoperability can be achieved by implementations that expect no more precision or range than these provide, in the sense that implementations will approximate JSON numbers within the expected precision.  A JSON number such as 1E400 or 3.141592653589793238462643383279 may indicate potential interoperability problems, since it suggests that the software that created it expects receiving software to have greater capabilities for numeric magnitude and precision than is widely available. Note that when such software is used, numbers that are integers and are in the range [-(2**53)+1, (2**53)-1] are interoperable in the sense that implementations will agree exactly on their numeric  values."

Given the wording of the RFC, I don't think these are conformance issues as such. It's certainly helpful, though, for users to know which JSON tools are capable of preserving the precision of large numbers. But to do that I think you need to augment the tests to verify that the tools support an API for _accessing_ the numbers without loss of precision, "get as int64_t" or "get as double" wouldn't do. 

Just FYI, I'm planning to add support for big integers. But probably not 5e-324 without loss of precision.

Best regards,
Daniel
